### ISSUE TITLE
Sunchipp Cars

### ISSUE THREAD

**Issue by Sunchipp** [Distance-Modding/Custom-Cars#1]
### What is the name of your car?

sunchipps_rat-rod (+more)

### What folder should it be in?

/Sunchipp Made

### Who made this car?

Me

### Where can we get your car?

https://drive.google.com/drive/folders/1-cm7jNPZA-UT-QQW_O350Lz3NRbs84uJ?usp=share_link

**Comment by Tribow** [comment]
Added all cars from the drive into the repo
I sorted the cars best I could based on the categories that are already in the repo. I did make a new folder for Wacky Races

**Comment by Sunchipp** [comment]
> Added all cars from the drive into the repo I sorted the cars best I could based on the categories that are already in the repo. I did make a new folder for Wacky Races

I appreciate that dude. but you do know if you needed a contributor you could've let me know on Discord XD I'd be more than glad to help you out in this, save you some of the work that was done
